# Generated by Django 6.0 on 2025-12-25 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('correo', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('nombre_completo', models.CharField(blank=True, max_length=255, verbose_name='Nombre Completo')),
                ('tipo_usuario', models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('EXTERNO', 'Externo')], default='EXTERNO', max_length=20, verbose_name='Tipo de Usuario')),
                ('es_administrador', models.BooleanField(default=False, verbose_name='Es Administrador')),
                ('esta_activo', models.BooleanField(default=True, verbose_name='Está Activo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Es Staff')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
