# Generated by Django 6.0 on 2025-12-25 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransaccionBlockchain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_transaccion', models.CharField(choices=[('REGISTRO_PRODUCTO', 'Registro de Producto'), ('MOVIMIENTO_INVENTARIO', 'Movimiento de Inventario'), ('ACTUALIZACION_PRECIO', 'Actualización de Precio'), ('TRANSFERENCIA_EMPRESA', 'Transferencia entre Empresas')], max_length=50, verbose_name='Tipo de Transacción')),
                ('hash_transaccion', models.CharField(help_text='Hash único de la transacción en blockchain', max_length=66, unique=True, verbose_name='Hash de Transacción')),
                ('bloque_numero', models.BigIntegerField(blank=True, null=True, verbose_name='Número de Bloque')),
                ('datos_transaccion', models.JSONField(help_text='Información almacenada en la transacción', verbose_name='Datos de la Transacción')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('FALLIDA', 'Fallida')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('gas_utilizado', models.BigIntegerField(blank=True, null=True, verbose_name='Gas Utilizado')),
                ('costo_transaccion', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True, verbose_name='Costo de Transacción (ETH)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Confirmación')),
                ('direccion_remitente', models.CharField(blank=True, max_length=42, verbose_name='Dirección Remitente')),
                ('direccion_contrato', models.CharField(blank=True, max_length=42, verbose_name='Dirección del Contrato')),
                ('movimiento_inventario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones_blockchain', to='inventario.movimientoinventario', verbose_name='Movimiento de Inventario')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones_blockchain', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Transacción Blockchain',
                'verbose_name_plural': 'Transacciones Blockchain',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaBlockchain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verificado', models.BooleanField(default=False, verbose_name='Verificado')),
                ('datos_blockchain', models.JSONField(help_text='Datos recuperados directamente de la blockchain', verbose_name='Datos desde Blockchain')),
                ('datos_base_datos', models.JSONField(help_text='Datos almacenados en la base de datos local', verbose_name='Datos desde Base de Datos')),
                ('coinciden', models.BooleanField(default=True, verbose_name='Datos Coinciden')),
                ('discrepancias', models.JSONField(default=list, help_text='Lista de discrepancias encontradas', verbose_name='Discrepancias')),
                ('fecha_auditoria', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Auditoría')),
                ('auditado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Auditado Por')),
                ('transaccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='blockchain.transaccionblockchain', verbose_name='Transacción')),
            ],
            options={
                'verbose_name': 'Auditoría Blockchain',
                'verbose_name_plural': 'Auditorías Blockchain',
                'ordering': ['-fecha_auditoria'],
            },
        ),
        migrations.AddIndex(
            model_name='transaccionblockchain',
            index=models.Index(fields=['hash_transaccion'], name='blockchain__hash_tr_fa98fd_idx'),
        ),
        migrations.AddIndex(
            model_name='transaccionblockchain',
            index=models.Index(fields=['estado'], name='blockchain__estado_5c383a_idx'),
        ),
    ]
