# Generated by Django 6.0 on 2025-12-25 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0, verbose_name='Cantidad en Stock')),
                ('cantidad_minima', models.IntegerField(default=10, help_text='Nivel mínimo de stock antes de reordenar', verbose_name='Cantidad Mínima')),
                ('ubicacion_bodega', models.CharField(blank=True, max_length=100, verbose_name='Ubicación en Bodega')),
                ('fecha_ultima_entrada', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Última Entrada')),
                ('fecha_ultima_salida', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Última Salida')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_inventario', to='empresas.empresa', verbose_name='Empresa')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_inventario', to='productos.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Registro de Inventario',
                'verbose_name_plural': 'Registros de Inventario',
                'ordering': ['-fecha_actualizacion'],
                'unique_together': {('producto', 'empresa')},
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('AJUSTE', 'Ajuste')], max_length=20, verbose_name='Tipo de Movimiento')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo del Movimiento')),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Movimiento')),
                ('hash_blockchain', models.CharField(blank=True, help_text='Hash de la transacción registrada en blockchain', max_length=66, verbose_name='Hash en Blockchain')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Registró')),
                ('registro_inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.registroinventario', verbose_name='Registro de Inventario')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-fecha_movimiento'],
            },
        ),
    ]
