# Generated by Django 6.0 on 2025-12-25 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código del Producto')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del Producto')),
                ('caracteristicas', models.TextField(blank=True, verbose_name='Características')),
                ('precio_usd', models.DecimalField(decimal_places=2, help_text='Precio en dólares americanos', max_digits=12, verbose_name='Precio en USD')),
                ('precio_cop', models.DecimalField(blank=True, decimal_places=2, help_text='Precio en pesos colombianos', max_digits=12, null=True, verbose_name='Precio en COP')),
                ('precio_eur', models.DecimalField(blank=True, decimal_places=2, help_text='Precio en euros', max_digits=12, null=True, verbose_name='Precio en EUR')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen del Producto')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='empresas.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
    ]
