# Generated by Django 6.0 on 2025-12-25 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_analisis', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Análisis')),
                ('productos_analizados', models.IntegerField(verbose_name='Productos Analizados')),
                ('recomendaciones', models.JSONField(default=list, help_text='Lista de recomendaciones generadas por IA', verbose_name='Recomendaciones')),
                ('productos_bajo_stock', models.JSONField(default=list, verbose_name='Productos Bajo Stock')),
                ('productos_sobrestock', models.JSONField(default=list, verbose_name='Productos con Sobrestock')),
                ('proyeccion_demanda', models.JSONField(default=dict, verbose_name='Proyección de Demanda')),
                ('ahorro_potencial', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Ahorro Potencial (USD)')),
            ],
            options={
                'verbose_name': 'Análisis de Inventario',
                'verbose_name_plural': 'Análisis de Inventario',
                'ordering': ['-fecha_analisis'],
            },
        ),
        migrations.CreateModel(
            name='ConsultaChatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField(verbose_name='Pregunta')),
                ('respuesta', models.TextField(verbose_name='Respuesta')),
                ('contexto', models.JSONField(default=dict, help_text='Información contextual utilizada para generar la respuesta', verbose_name='Contexto')),
                ('fecha_consulta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Consulta')),
                ('tiempo_respuesta', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Tiempo de Respuesta (segundos)')),
                ('satisfaccion_usuario', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Satisfacción del Usuario (1-5)')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_chatbot', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Consulta de Chatbot',
                'verbose_name_plural': 'Consultas de Chatbot',
                'ordering': ['-fecha_consulta'],
            },
        ),
        migrations.CreateModel(
            name='PrediccionPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_actual', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio Actual')),
                ('precio_predicho_30_dias', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio Predicho 30 días')),
                ('precio_predicho_60_dias', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio Predicho 60 días')),
                ('precio_predicho_90_dias', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio Predicho 90 días')),
                ('tendencia', models.CharField(choices=[('ALZA', 'Alza'), ('BAJA', 'Baja'), ('ESTABLE', 'Estable')], max_length=20, verbose_name='Tendencia')),
                ('confianza_prediccion', models.DecimalField(decimal_places=2, help_text='Porcentaje de confianza del modelo (0-100)', max_digits=5, verbose_name='Confianza de la Predicción (%)')),
                ('factores_considerados', models.JSONField(default=dict, help_text='Factores que influyeron en la predicción', verbose_name='Factores Considerados')),
                ('fecha_prediccion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Predicción')),
                ('modelo_utilizado', models.CharField(default='GPT-4', max_length=100, verbose_name='Modelo Utilizado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicciones_precio', to='productos.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Predicción de Precio',
                'verbose_name_plural': 'Predicciones de Precios',
                'ordering': ['-fecha_prediccion'],
            },
        ),
    ]
