# Generated by Django 6.0 on 2025-12-27 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccionIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_accion', models.CharField(choices=[('consulta_stock', 'Consulta de Stock'), ('generar_pdf', 'Generar PDF'), ('enviar_email', 'Enviar Email'), ('registrar_movimiento', 'Registrar Movimiento'), ('analisis', 'Análisis de Datos')], max_length=50)),
                ('parametros', models.JSONField(default=dict)),
                ('resultado', models.JSONField(default=dict)),
                ('exitoso', models.BooleanField(default=True)),
                ('fecha_ejecucion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Acción IA',
                'verbose_name_plural': 'Acciones IA',
                'db_table': 'ia_accion',
                'ordering': ['-fecha_ejecucion'],
            },
        ),
        migrations.CreateModel(
            name='ConversacionIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_ia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversación IA',
                'verbose_name_plural': 'Conversaciones IA',
                'db_table': 'ia_conversacion',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='MensajeIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('user', 'Usuario'), ('assistant', 'Asistente'), ('system', 'Sistema')], max_length=20)),
                ('contenido', models.TextField()),
                ('metadatos', models.JSONField(blank=True, default=dict)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='ia.conversacionia')),
            ],
            options={
                'verbose_name': 'Mensaje IA',
                'verbose_name_plural': 'Mensajes IA',
                'db_table': 'ia_mensaje',
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.DeleteModel(
            name='AnalisisInventario',
        ),
        migrations.RemoveField(
            model_name='prediccionprecio',
            name='producto',
        ),
        migrations.AddField(
            model_name='accionia',
            name='mensaje',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones', to='ia.mensajeia'),
        ),
        migrations.DeleteModel(
            name='ConsultaChatbot',
        ),
        migrations.DeleteModel(
            name='PrediccionPrecio',
        ),
    ]
